baseURL = "http://fernandonobel.xyz/"
languageCode = "es-es"
title = "Fernando NÃ³bel"

[permalinks]
  blog = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Inicio"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Etiquetas"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Bienvenidos a la gestalt"

[taxonomies]
  tag = "tags"
